[package]
name = "cargo-checkmate"
version = "0.1.3"
authors = ["nathan <nathan+dev@electriccoin.co>"]
edition = "2018"
description = "checkmate checks all the things - comprehensive out-of-the-box safety & hygiene checks."
license = "MIT"
homepage = "https://github.com/nathan-at-least/cargo-checkmate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abscissa_core = "0.5.2"
cargo-audit = "0.14.1"
enum-iterator = "0.6.0"

[dev-dependencies]
test-case = "1.0.0"
